version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - CV-Europass-20160308-CarneirinhoGuiomar-EN.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js
