version: 0.1

phases:
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - favicon.ico
    - CV-Europass-20160308-CarneirinhoGuiomar-EN.pdf
    - styles/main.css
    - images/*
    
